
import com.toedter.calendar.JCalendar;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;
import java.text.MessageFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ql_chuyenbay extends javax.swing.JFrame {
    private int CB_id;
    //static Date CB_ngaybay;

    /**
     * Creates new form chuyen_bay
     */
    public ql_chuyenbay() {
        initComponents();
        hienthi_cb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        CB_noidi = new javax.swing.JComboBox<>();
        CB_noiden = new javax.swing.JComboBox<>();
        luucb_nut = new javax.swing.JButton();
        xoacb_nut = new javax.swing.JButton();
        udcb_nut = new javax.swing.JButton();
        backcb_nut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsccb = new javax.swing.JTable();
        CB_ghengoi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timcb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CB_ngaybay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        loctheongay = new javax.swing.JTextField();
        lammoi_cb = new javax.swing.JButton();
        thoat_cb = new javax.swing.JButton();
        print_cb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ CHUYẾN BAY");

        jTextField11.setBackground(new java.awt.Color(153, 204, 255));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        CB_noidi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SB. Cần Thơ", "SB. Phú Quốc", "SB. Tân Sơn Nhất", "SB. Vân Đồn", "SB. Nội Bài", "SB. Cát Bi", "SB. Vinh", "SB. Phú Bài", "SB. Đà Nẵng", "SB. Cam Ranh" }));
        CB_noidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_noidiActionPerformed(evt);
            }
        });

        CB_noiden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SB. Cần Thơ", "SB. Phú Quốc", "SB. Tân Sơn Nhất", "SB. Vân Đồn", "SB. Nội Bài", "SB. Cát Bi", "SB. Vinh", "SB. Phú Bài", "SB. Đà Nẵng", "SB. Cam Ranh" }));
        CB_noiden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_noidenActionPerformed(evt);
            }
        });

        luucb_nut.setText("Lưu");
        luucb_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luucb_nutMouseClicked(evt);
            }
        });
        luucb_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luucb_nutActionPerformed(evt);
            }
        });

        xoacb_nut.setText("Xoá");
        xoacb_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoacb_nutMouseClicked(evt);
            }
        });
        xoacb_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoacb_nutActionPerformed(evt);
            }
        });

        udcb_nut.setText("Cập Nhật");
        udcb_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                udcb_nutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                udcb_nutMouseEntered(evt);
            }
        });
        udcb_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udcb_nutActionPerformed(evt);
            }
        });

        backcb_nut.setText("Quay lại");
        backcb_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backcb_nutMouseClicked(evt);
            }
        });
        backcb_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backcb_nutActionPerformed(evt);
            }
        });

        dsccb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsccb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsccbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsccb);

        CB_ghengoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ghengoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Nơi đến: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Nơi xuất phát: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Ngày bay: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Số ghế ngồi: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Danh sách các chuyến bay");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        timcb.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                timcbCaretUpdate(evt);
            }
        });
        timcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timcbMouseClicked(evt);
            }
        });
        timcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timcbActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Tìm chuyến bay:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Lọc chuyến bay theo ngày:");

        loctheongay.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                loctheongayCaretUpdate(evt);
            }
        });
        loctheongay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loctheongayMouseClicked(evt);
            }
        });
        loctheongay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loctheongayActionPerformed(evt);
            }
        });

        lammoi_cb.setText("Làm mới");
        lammoi_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lammoi_cbMouseClicked(evt);
            }
        });

        thoat_cb.setText("Thoát");
        thoat_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoat_cbMouseClicked(evt);
            }
        });
        thoat_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat_cbActionPerformed(evt);
            }
        });

        print_cb.setText("Print");
        print_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_cbMouseClicked(evt);
            }
        });
        print_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_cbActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\CT46701_B1910461_B1910458\\anhmb.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CB_noiden, 0, 188, Short.MAX_VALUE)
                            .addComponent(CB_noidi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_ngaybay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(luucb_nut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xoacb_nut)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(udcb_nut)
                                .addGap(36, 36, 36)
                                .addComponent(backcb_nut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CB_ghengoi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(lammoi_cb)
                                .addGap(81, 81, 81)
                                .addComponent(print_cb)
                                .addGap(81, 81, 81)
                                .addComponent(thoat_cb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(timcb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(loctheongay, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(350, 350, 350))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CB_noidi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CB_noiden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CB_ngaybay)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(CB_ghengoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(luucb_nut)
                                .addComponent(xoacb_nut)
                                .addComponent(udcb_nut)
                                .addComponent(backcb_nut))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loctheongay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lammoi_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(print_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoat_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection conn=null;
    PreparedStatement pStmt=null;
    ResultSet rs=null, rs1=null;
    Statement Stmt=null, Stmt1=null;
    
        private void hienthi_cb(){
        try{
          conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
          Stmt = conn.createStatement();
          rs=Stmt.executeQuery("Select * from ql_chuyenbay");
          dsccb.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e){
            
        }
    }
    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void CB_noidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_noidiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_noidiActionPerformed

    private void CB_noidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_noidenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_noidenActionPerformed


    private void luucb_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luucb_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luucb_nutActionPerformed
 
    private void xoacb_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoacb_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoacb_nutActionPerformed

    private void udcb_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udcb_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udcb_nutActionPerformed

    private void backcb_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backcb_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backcb_nutActionPerformed

    private void CB_ghengoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ghengoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_ghengoiActionPerformed
    int dem=0;
    private void dem_cb(){
        try{
            Stmt=conn.createStatement();
            rs1= Stmt.executeQuery("select Max(CB_id) from ql_chuyenbay");
            rs1.next();
            dem=rs1.getInt(1)+1;
        }
        catch(Exception e){}
    
    }
    private void xoa_cb(){
       
        CB_ngaybay.setText("");
        CB_ghengoi.setText("");
    
    }
    private void luucb_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luucb_nutMouseClicked
        if( CB_ngaybay.getText().isEmpty() || CB_ghengoi.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Lỗi");
        }else{
            try {
                dem_cb();
                String connStr="jdbc:mysql://localhost:3306/ariline_data?user=root";
                Connection conn = DriverManager.getConnection(connStr);
                CallableStatement cStmt11 = conn.prepareCall("{call themCB(?,?,?,?,?)}");
                cStmt11.setInt(1, dem);
                cStmt11.setString(2, CB_noidi.getSelectedItem().toString());
                cStmt11.setString(3, CB_noiden.getSelectedItem().toString());  
                cStmt11.setString(4, CB_ngaybay.getText());                  
                cStmt11.setString(5, CB_ghengoi.getText());
                cStmt11.execute();
                ResultSet rs= cStmt11.executeQuery("SELECT * FROM ql_chuyenbay");
                JOptionPane.showMessageDialog(this,"Đã thêm chuyến bay");
                conn.close();              
                hienthi_cb();
                 key=0;
                 xoa_cb();
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        };
    }//GEN-LAST:event_luucb_nutMouseClicked
 int key=0;    
    private void xoacb_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoacb_nutMouseClicked
        if(key==0){
            JOptionPane.showMessageDialog(this,"Chọn 1 chuyến bay");
        }
        else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
                CallableStatement cStmt12 = conn.prepareCall("{call xoaCB(?)}");
                cStmt12.setInt(1, key);//800
                cStmt12.execute();
                ResultSet rs3= cStmt12.executeQuery("SELECT * FROM ql_chuyenbay");
                key=0;
                JOptionPane.showMessageDialog(this,"Đã xoá hành khách");
                xoa_cb();                
                hienthi_cb();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_xoacb_nutMouseClicked


    private void udcb_nutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udcb_nutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_udcb_nutMouseEntered

    private void udcb_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udcb_nutMouseClicked
        if(key==0 || CB_ngaybay.getText().isEmpty() || CB_ghengoi.getText().isEmpty())
       {
            JOptionPane.showMessageDialog(this,"Chọn 1 vé");
        }
        else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
                PreparedStatement Ud=conn.prepareStatement("Update ql_chuyenbay set CB_noidi=?, CB_noiden=?, CB_ngaybay=?, CB_soGhengoi=? where CB_id=?");
                Ud.setInt(5, key);
                Ud.setString(1, CB_noidi.getSelectedItem().toString()); 
                Ud.setString(2,CB_noiden.getSelectedItem().toString()); 
                Ud.setString(3, CB_ngaybay.getText());
                Ud.setString(4, CB_ghengoi.getText());
                
                int row=Ud.executeUpdate();
                JOptionPane.showMessageDialog(this,"Đã cập nhật hành khách");
                conn.close();
                hienthi_cb();
                key=0;
                xoa_cb();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_udcb_nutMouseClicked

    private void backcb_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backcb_nutMouseClicked
              new chon_dv().setVisible(true);
               this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backcb_nutMouseClicked

    private void dsccbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsccbMouseClicked
                DefaultTableModel model=(DefaultTableModel)dsccb.getModel();
                int myindex=dsccb.getSelectedRow();
                key=Integer.valueOf(model.getValueAt(myindex,0).toString());             
                CB_noidi.setSelectedItem(model.getValueAt(myindex,1).toString());
                CB_noiden.setSelectedItem(model.getValueAt(myindex,2).toString());
                CB_ngaybay.setText(model.getValueAt(myindex,3).toString());
                CB_ghengoi.setText(model.getValueAt(myindex,4).toString());
                
       
    }//GEN-LAST:event_dsccbMouseClicked
        private void search_cb(){
           try{
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
             Stmt = conn.createStatement();
             rs=Stmt.executeQuery("Select * from ql_chuyenbay where CB_id like '"+timcb.getText()+"%'");
             dsccb.setModel(DbUtils.resultSetToTableModel(rs));
           }
           catch (Exception e){
    }
    }
    private void loc_cb(){
           try{
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
             Stmt = conn.createStatement();
             rs=Stmt.executeQuery("Select * from ql_chuyenbay where CB_ngaybay like '"+loctheongay.getText()+"%'");
             dsccb.setModel(DbUtils.resultSetToTableModel(rs));
           }
           catch (Exception e){
    }
    }
    private void timcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timcbActionPerformed
        search_cb();
    }//GEN-LAST:event_timcbActionPerformed

    private void timcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timcbMouseClicked
        search_cb();
    }//GEN-LAST:event_timcbMouseClicked

    private void timcbCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_timcbCaretUpdate
        search_cb();
    }//GEN-LAST:event_timcbCaretUpdate

    private void loctheongayCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_loctheongayCaretUpdate
        loc_cb();
    }//GEN-LAST:event_loctheongayCaretUpdate

    private void loctheongayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loctheongayMouseClicked
        loc_cb();
    }//GEN-LAST:event_loctheongayMouseClicked

    private void loctheongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loctheongayActionPerformed
         loc_cb();
    }//GEN-LAST:event_loctheongayActionPerformed

    private void lammoi_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lammoi_cbMouseClicked
        hienthi_cb();
        timcb.setText("");
    }//GEN-LAST:event_lammoi_cbMouseClicked

    private void thoat_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoat_cbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_thoat_cbMouseClicked
        private JFrame frame;
    private void thoat_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat_cbActionPerformed
        frame = new JFrame("Thoát");
        if (JOptionPane.showConfirmDialog(frame, "Xác nhận nếu bạn muốn thoát","Hệ thống đặt vé máy bay",
             JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_thoat_cbActionPerformed

    private void print_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_cbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_print_cbMouseClicked

    private void print_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_cbActionPerformed
       MessageFormat header = new MessageFormat("Bảng in danh sách các chuyến bay");
       MessageFormat footer = new MessageFormat("Trang {0, number, integer}");
       try{
           dsccb.print(JTable.PrintMode.NORMAL,header, footer);
       }
       catch(java.awt.print.PrinterAbortException e){
           System.err.format("No Printer found", e.getMessage());
       } catch (PrinterException ex) {
            Logger.getLogger(ql_chuyenbay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ql_chuyenbay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ql_chuyenbay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ql_chuyenbay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ql_chuyenbay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ql_chuyenbay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CB_ghengoi;
    private javax.swing.JTextField CB_ngaybay;
    private javax.swing.JComboBox<String> CB_noiden;
    private javax.swing.JComboBox<String> CB_noidi;
    private javax.swing.JButton backcb_nut;
    private javax.swing.JTable dsccb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JButton lammoi_cb;
    private javax.swing.JTextField loctheongay;
    private javax.swing.JButton luucb_nut;
    private javax.swing.JButton print_cb;
    private javax.swing.JButton thoat_cb;
    private javax.swing.JTextField timcb;
    private javax.swing.JButton udcb_nut;
    private javax.swing.JButton xoacb_nut;
    // End of variables declaration//GEN-END:variables

   private void execute() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void hien_thi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
