import com.toedter.calendar.JCalendar;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;
import java.text.MessageFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ql_hanhkhach1 extends javax.swing.JFrame {
    private int HK_id;
    private Component frame;

    /**
     * Creates new form ql_hanhkhach1
     */
    public ql_hanhkhach1() {
        initComponents();
        hienthi_hk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loc_lv = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        HK_qt = new javax.swing.JComboBox<>();
        HK_gt = new javax.swing.JComboBox<>();
        luu_nut = new javax.swing.JButton();
        xoa_nut = new javax.swing.JButton();
        capnhat_nut = new javax.swing.JButton();
        quaylai_nut = new javax.swing.JButton();
        HK_ht = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dshk = new javax.swing.JTable();
        HK_sodt = new javax.swing.JTextField();
        HK_shc = new javax.swing.JTextField();
        HK_dc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tim_hk = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        lam_moi = new javax.swing.JButton();
        loc_gt = new javax.swing.JComboBox<>();
        print_cb = new javax.swing.JButton();
        thoat_cb = new javax.swing.JButton();

        loc_lv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TN_t", "TN_vip", "NN_t", "NN_vip" }));
        loc_lv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loc_lvItemStateChanged(evt);
            }
        });
        loc_lv.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                loc_lvCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        loc_lv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_lvActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        HK_qt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Việt Nam", "Campuchia", "Indonexia", "Pháp", "Đức", "Anh", "Bỉ", "Trung Quốc", "Thái Lan", "Hàn Quốc", "Nhật Bản" }));
        HK_qt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HK_qtActionPerformed(evt);
            }
        });

        HK_gt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        HK_gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HK_gtActionPerformed(evt);
            }
        });

        luu_nut.setText("Lưu");
        luu_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luu_nutMouseClicked(evt);
            }
        });
        luu_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luu_nutActionPerformed(evt);
            }
        });

        xoa_nut.setText("Xoá");
        xoa_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoa_nutMouseClicked(evt);
            }
        });
        xoa_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_nutActionPerformed(evt);
            }
        });

        capnhat_nut.setText("Cập Nhật");
        capnhat_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capnhat_nutMouseClicked(evt);
            }
        });
        capnhat_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhat_nutActionPerformed(evt);
            }
        });

        quaylai_nut.setText("Quay lại");
        quaylai_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quaylai_nutMouseClicked(evt);
            }
        });
        quaylai_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylai_nutActionPerformed(evt);
            }
        });

        HK_ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HK_htActionPerformed(evt);
            }
        });

        dshk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dshk.setRowHeight(25);
        dshk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dshkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dshk);

        HK_sodt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HK_sodtActionPerformed(evt);
            }
        });

        HK_shc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HK_shcActionPerformed(evt);
            }
        });

        HK_dc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HK_dcActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Họ tên:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Giới tính: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Số hộ chiếu: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Số điện thoại: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Địa chỉ: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Quốc tịch: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Danh sách hành khách");

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\qtdl\\abc1.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("QUẢN LÝ HÀNH KHÁCH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Tìm kiếm hành khách");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Lọc theo giới tính");

        tim_hk.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tim_hkCaretUpdate(evt);
            }
        });
        tim_hk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tim_hkActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lam_moi.setText("Làm mới");
        lam_moi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lam_moiMouseClicked(evt);
            }
        });
        lam_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lam_moiActionPerformed(evt);
            }
        });

        loc_gt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        loc_gt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loc_gtItemStateChanged(evt);
            }
        });
        loc_gt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                loc_gtCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        loc_gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_gtActionPerformed(evt);
            }
        });

        print_cb.setText("Print");
        print_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_cbMouseClicked(evt);
            }
        });
        print_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_cbActionPerformed(evt);
            }
        });

        thoat_cb.setText("Thoát");
        thoat_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoat_cbMouseClicked(evt);
            }
        });
        thoat_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(luu_nut)
                        .addGap(27, 27, 27)
                        .addComponent(xoa_nut)
                        .addGap(34, 34, 34)
                        .addComponent(capnhat_nut)
                        .addGap(37, 37, 37)
                        .addComponent(quaylai_nut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HK_ht, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HK_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HK_shc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HK_sodt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HK_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HK_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tim_hk, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(327, 327, 327))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jToggleButton1))
                                .addContainerGap(55, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(638, 638, 638)
                        .addComponent(loc_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(114, 114, 114)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lam_moi)
                .addGap(93, 93, 93)
                .addComponent(print_cb)
                .addGap(81, 81, 81)
                .addComponent(thoat_cb)
                .addGap(369, 369, 369))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HK_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(HK_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(HK_shc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(HK_sodt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(HK_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(HK_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(luu_nut)
                            .addComponent(xoa_nut)
                            .addComponent(capnhat_nut)
                            .addComponent(quaylai_nut))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tim_hk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(loc_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lam_moi)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(print_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thoat_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection conn=null;
    PreparedStatement pStmt=null;
    ResultSet rs=null, rs1=null;
    Statement Stmt=null, Stmt1=null;
    
    private void HK_qtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HK_qtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HK_qtActionPerformed

    private void HK_gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HK_gtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HK_gtActionPerformed
    int dem=0;
    private void dem_hk(){
        try{
            Stmt=conn.createStatement();
            rs1= Stmt.executeQuery("select Max(HK_id) from ql_hanhkhach");
            rs1.next();
            dem=rs1.getInt(1)+100;
        }
        catch(Exception e){}
    }
    
    private void xoa_hk(){
        HK_ht.setText("");
        HK_shc.setText("");
        HK_dc.setText("");
        HK_sodt.setText("");
    }
    
    private void luu_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luu_nutMouseClicked
        if(HK_ht.getText().isEmpty() || HK_shc.getText().isEmpty() || HK_dc.getText().isEmpty() || HK_sodt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Nhập thiếu");
        }else{
            try {
                dem_hk();
                String connStr="jdbc:mysql://localhost/ariline_data?user=root";
                Connection conn = DriverManager.getConnection(connStr);
                CallableStatement cStmt10 = conn.prepareCall("{call themHK(?,?,?,?,?,?,?)}");
                cStmt10.setInt(1, dem);
                cStmt10.setString(2, HK_ht.getText());
                cStmt10.setString(3, HK_gt.getSelectedItem().toString());
                cStmt10.setString(4, HK_shc.getText());
                cStmt10.setString(5, HK_sodt.getText());
                cStmt10.setString(6, HK_dc.getText());
                cStmt10.setString(7, HK_qt.getSelectedItem().toString());
                cStmt10.execute();
                ResultSet rs10 = cStmt10.executeQuery("SELECT * FROM ql_hanhkhach");
                JOptionPane.showMessageDialog(this,"Đã thêm hành khách");
                conn.close();
                hienthi_hk();
                key=0;
                xoa_hk();
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        };
    }//GEN-LAST:event_luu_nutMouseClicked

    private void luu_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luu_nutActionPerformed

    }//GEN-LAST:event_luu_nutActionPerformed
    int key=0;
    private void xoa_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_nutMouseClicked
        if(key==0){
            JOptionPane.showMessageDialog(this,"Chọn 1 hành khách");
        }
        else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
                CallableStatement cStmt11 = conn.prepareCall("{call xoaHK(?)}");
                cStmt11.setInt(1, key);//800
                cStmt11.execute();
                ResultSet rs11 = cStmt11.executeQuery("SELECT * FROM ql_hanhkhach");
                key=0;
                JOptionPane.showMessageDialog(this,"Đã xoá hành khách");
                xoa_hk(); 
                hienthi_hk();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_xoa_nutMouseClicked
    
    private void hienthi_hk(){
        try{
          conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
          Stmt = conn.createStatement();
          rs=Stmt.executeQuery("Select * from ql_hanhkhach");
          dshk.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e){   
        }
    }
    
    private void xoa_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoa_nutActionPerformed

    private void capnhat_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capnhat_nutMouseClicked
         if(key==0 || HK_ht.getText().isEmpty() || HK_shc.getText().isEmpty() || HK_dc.getText().isEmpty() || HK_sodt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Chọn 1 hành khách và nhập đủ thông tin");
        }
        else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
                PreparedStatement Ud=conn.prepareStatement("Update ql_hanhkhach set HK_ten=?, HK_gioitinh=?, HK_sohochieu=?, HK_sdt=?, HK_diachi=?, HK_quoctich=? where HK_id=?");
                Ud.setInt(7, key);
                Ud.setString(1, HK_ht.getText());
                Ud.setString(2, HK_gt.getSelectedItem().toString());
                Ud.setString(3, HK_shc.getText());
                Ud.setString(4, HK_sodt.getText());
                Ud.setString(5, HK_dc.getText());
                Ud.setString(6, HK_qt.getSelectedItem().toString());
                int row=Ud.executeUpdate();
                JOptionPane.showMessageDialog(this,"Đã cập nhật hành khách");
                conn.close();
                hienthi_hk();
                key=0;
                xoa_hk();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_capnhat_nutMouseClicked

    private void capnhat_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhat_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capnhat_nutActionPerformed

    private void quaylai_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quaylai_nutMouseClicked
               new chon_dv().setVisible(true);
               this.dispose();
    }//GEN-LAST:event_quaylai_nutMouseClicked

    private void quaylai_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylai_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaylai_nutActionPerformed

    private void HK_htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HK_htActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HK_htActionPerformed

    private void dshkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dshkMouseClicked
                DefaultTableModel model=(DefaultTableModel)dshk.getModel();
                int myindex=dshk.getSelectedRow();
                key=Integer.valueOf(model.getValueAt(myindex,0).toString());
                HK_ht.setText(model.getValueAt(myindex,1).toString());
                HK_gt.setSelectedItem(model.getValueAt(myindex,2).toString());
                HK_shc.setText(model.getValueAt(myindex,3).toString());
                HK_sodt.setText(model.getValueAt(myindex,4).toString());
                HK_dc.setText(model.getValueAt(myindex,5).toString());
                HK_qt.setSelectedItem(model.getValueAt(myindex,6).toString());
    }//GEN-LAST:event_dshkMouseClicked

    private void HK_sodtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HK_sodtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HK_sodtActionPerformed

    private void HK_shcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HK_shcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HK_shcActionPerformed

    private void HK_dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HK_dcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HK_dcActionPerformed
    private void search_hk(){
           try{
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
             Stmt = conn.createStatement();
             rs=Stmt.executeQuery("Select * from ql_hanhkhach where HK_id like '"+tim_hk.getText()+"%'");
             dshk.setModel(DbUtils.resultSetToTableModel(rs));
           }
           catch (Exception e){
           }
    }

    private void tim_hkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tim_hkActionPerformed
                search_hk();
    }//GEN-LAST:event_tim_hkActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tim_hkCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tim_hkCaretUpdate
        search_hk();
    }//GEN-LAST:event_tim_hkCaretUpdate

    private void lam_moiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lam_moiMouseClicked
        hienthi_hk();
        tim_hk.setText("");
    }//GEN-LAST:event_lam_moiMouseClicked

    private void lam_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lam_moiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lam_moiActionPerformed
    private void chuacove(){
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
            Stmt = conn.createStatement();
            rs=Stmt.executeQuery("select * from ql_hanhkhach where HK_id NOT IN (select distinct HK_id from ql_datve)");
            dshk.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e){
       }
    }    
    
    private void loc_gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_gtActionPerformed
        tim_gt();
    }//GEN-LAST:event_loc_gtActionPerformed

    private void loc_lvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_lvActionPerformed
        tim_hkloaive();
    }//GEN-LAST:event_loc_lvActionPerformed

    private void loc_gtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loc_gtItemStateChanged
 
    }//GEN-LAST:event_loc_gtItemStateChanged

    private void loc_lvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loc_lvItemStateChanged

    }//GEN-LAST:event_loc_lvItemStateChanged

    private void loc_gtCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_loc_gtCaretPositionChanged
        JOptionPane.showMessageDialog(this,"Không có");
    }//GEN-LAST:event_loc_gtCaretPositionChanged

    private void loc_lvCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_loc_lvCaretPositionChanged
        JOptionPane.showMessageDialog(this,"Không có");
    }//GEN-LAST:event_loc_lvCaretPositionChanged

    private void print_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_cbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_print_cbMouseClicked

    private void print_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_cbActionPerformed
        MessageFormat header = new MessageFormat("Bảng in danh sách các hành khách");
        MessageFormat footer = new MessageFormat("Trang {0, number, integer}");
        try{
            dshk.print(JTable.PrintMode.NORMAL,header, footer);
        }
        catch(java.awt.print.PrinterAbortException e){
            System.err.format("No Printer found", e.getMessage());
        } catch (PrinterException ex) {
            Logger.getLogger(ql_chuyenbay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_cbActionPerformed

    private void thoat_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoat_cbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_thoat_cbMouseClicked

    private void thoat_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat_cbActionPerformed
        frame = new JFrame("Thoát");
        if (JOptionPane.showConfirmDialog(frame, "Xác nhận nếu bạn muốn thoát","Hệ thống đặt vé máy bay",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_thoat_cbActionPerformed
    
    private void tim_gt(){
       try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
         Stmt = conn.createStatement();
         rs=Stmt.executeQuery("select * from ql_hanhkhach where HK_gioitinh= '"+loc_gt.getSelectedItem().toString()+"'");
         dshk.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch (Exception e){
       }
    }
     private void tim_hkloaive(){
       try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
         Stmt = conn.createStatement();
         rs=Stmt.executeQuery("select * from ql_datve where LV_loai= '"+loc_lv.getSelectedItem().toString()+"'");
         dshk.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch (Exception e){
       }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ql_hanhkhach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ql_hanhkhach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ql_hanhkhach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ql_hanhkhach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ql_hanhkhach1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HK_dc;
    private javax.swing.JComboBox<String> HK_gt;
    private javax.swing.JTextField HK_ht;
    private javax.swing.JComboBox<String> HK_qt;
    private javax.swing.JTextField HK_shc;
    private javax.swing.JTextField HK_sodt;
    private javax.swing.JButton capnhat_nut;
    private javax.swing.JTable dshk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton lam_moi;
    private javax.swing.JComboBox<String> loc_gt;
    private javax.swing.JComboBox<String> loc_lv;
    private javax.swing.JButton luu_nut;
    private javax.swing.JButton print_cb;
    private javax.swing.JButton quaylai_nut;
    private javax.swing.JButton thoat_cb;
    private javax.swing.JTextField tim_hk;
    private javax.swing.JButton xoa_nut;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void hien_thi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
