import com.toedter.calendar.JCalendar;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;
import java.text.MessageFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ql_ve extends javax.swing.JFrame {
    private int DV_id;
    private JFrame frame;
    /**
     * Creates new form ql_datve
     */
    public ql_ve() {
        initComponents();
        hienthi_dv();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dat = new javax.swing.JButton();
        huy = new javax.swing.JButton();
        quaylai_nut = new javax.swing.JButton();
        hk_ht = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsdv = new javax.swing.JTable();
        dv_sl = new javax.swing.JTextField();
        hk_shc = new javax.swing.JTextField();
        hk_id = new javax.swing.JTextField();
        dv_ngaydat = new javax.swing.JTextField();
        cb_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dt_ngaymax = new javax.swing.JRadioButton();
        dt_ngay = new javax.swing.JRadioButton();
        tinh_tien = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lv_loai = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        hk_chuacove = new javax.swing.JRadioButton();
        lam_moi = new javax.swing.JButton();
        ud_ve = new javax.swing.JButton();
        hk_qt = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tim_ve = new javax.swing.JTextField();
        loaive = new javax.swing.JButton();
        loc_lv = new javax.swing.JComboBox<>();
        print_cb = new javax.swing.JButton();
        thoat_cb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        dat.setText("Đặt vé");
        dat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datMouseClicked(evt);
            }
        });
        dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datActionPerformed(evt);
            }
        });

        huy.setText("Huỷ vé");
        huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huyMouseClicked(evt);
            }
        });
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });

        quaylai_nut.setText("Quay lại");
        quaylai_nut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quaylai_nutMouseClicked(evt);
            }
        });
        quaylai_nut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylai_nutActionPerformed(evt);
            }
        });

        hk_ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hk_htActionPerformed(evt);
            }
        });

        dsdv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsdvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsdv);

        dv_sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dv_slActionPerformed(evt);
            }
        });

        hk_shc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hk_shcActionPerformed(evt);
            }
        });

        hk_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hk_idActionPerformed(evt);
            }
        });

        dv_ngaydat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dv_ngaydatActionPerformed(evt);
            }
        });

        cb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_idActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("ID hành khách: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("ĐẶT VÉ");

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\qtdl\\abc.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Họ Tên: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Số hộ chiếu: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("ID chuyến bay: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Số lượng: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Quốc tịch: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Danh sách đặt vé");

        dt_ngaymax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dt_ngaymax.setText("Doanh thu trong ngày cao nhất");
        dt_ngaymax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dt_ngaymaxMouseClicked(evt);
            }
        });
        dt_ngaymax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_ngaymaxActionPerformed(evt);
            }
        });

        dt_ngay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dt_ngay.setText("Doanh thu trong ngày");
        dt_ngay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dt_ngayMouseClicked(evt);
            }
        });
        dt_ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_ngayActionPerformed(evt);
            }
        });

        tinh_tien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tinh_tien.setText("Tính tiền mỗi hành khách phải trả");
        tinh_tien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tinh_tienMouseClicked(evt);
            }
        });
        tinh_tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinh_tienActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Ngày đặt");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Loại vé");

        lv_loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TN_t", "TN_vip", "NN_t", "NN_vip" }));
        lv_loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lv_loaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Lọc theo loại vé");

        hk_chuacove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hk_chuacove.setText("Hành khách chưa đặt vé");
        hk_chuacove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hk_chuacoveActionPerformed(evt);
            }
        });

        lam_moi.setText("Làm mới");
        lam_moi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lam_moiMouseClicked(evt);
            }
        });
        lam_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lam_moiActionPerformed(evt);
            }
        });

        ud_ve.setText("Cập nhật");
        ud_ve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ud_veMouseClicked(evt);
            }
        });
        ud_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ud_veActionPerformed(evt);
            }
        });

        hk_qt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Việt Nam", "Campuchia", "Indonexia", "Pháp", "Đức", "Anh", "Bỉ", "Trung Quốc", "Thái Lan", "Hàn Quốc", "Nhật Bản" }));
        hk_qt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hk_qtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Tìm kiếm vé");

        tim_ve.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tim_veCaretUpdate(evt);
            }
        });
        tim_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tim_veActionPerformed(evt);
            }
        });

        loaive.setText("Xem loại và giá vé");
        loaive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loaiveMouseClicked(evt);
            }
        });

        loc_lv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TN_t", "TN_vip", "NN_t", "NN_vip" }));
        loc_lv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loc_lvItemStateChanged(evt);
            }
        });
        loc_lv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loc_lvMouseClicked(evt);
            }
        });
        loc_lv.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                loc_lvCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        loc_lv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_lvActionPerformed(evt);
            }
        });

        print_cb.setText("Print");
        print_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_cbMouseClicked(evt);
            }
        });
        print_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_cbActionPerformed(evt);
            }
        });

        thoat_cb.setText("Thoát");
        thoat_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoat_cbMouseClicked(evt);
            }
        });
        thoat_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hk_shc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dv_ngaydat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(hk_id, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hk_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hk_qt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dv_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loaive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lv_loai, 0, 188, Short.MAX_VALUE))))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dat)
                        .addGap(37, 37, 37)
                        .addComponent(huy)
                        .addGap(18, 18, 18)
                        .addComponent(ud_ve)
                        .addGap(18, 18, 18)
                        .addComponent(quaylai_nut)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hk_chuacove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dt_ngaymax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dt_ngay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tinh_tien, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tim_ve, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(loc_lv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(548, 548, 548))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lam_moi)
                        .addGap(60, 60, 60)
                        .addComponent(print_cb)
                        .addGap(69, 69, 69)
                        .addComponent(thoat_cb)
                        .addGap(210, 210, 210))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(hk_id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tinh_tien)
                                .addComponent(jLabel2))
                            .addGap(23, 23, 23)
                            .addComponent(dt_ngay))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tim_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(loc_lv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(5, 5, 5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(hk_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(cb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(hk_shc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(hk_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dv_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12))
                            .addComponent(dv_ngaydat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lv_loai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(loaive)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dat)
                            .addComponent(huy)
                            .addComponent(quaylai_nut)
                            .addComponent(ud_ve)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dt_ngaymax)))
                .addGap(0, 0, 0)
                .addComponent(hk_chuacove)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lam_moi)
                    .addComponent(print_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoat_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection conn=null;
    PreparedStatement pStmt=null;
    ResultSet rs=null, rs1=null;
    Statement Stmt=null, Stmt1=null;
    
    private void cb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_idActionPerformed

    private void dv_ngaydatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dv_ngaydatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dv_ngaydatActionPerformed
   int dem=0;
    private void dem_ve(){
        try{
            Stmt=conn.createStatement();
            rs1= Stmt.executeQuery("select Max(DV_id) from ql_datve");
            rs1.next();
            dem=rs1.getInt(1)+111;
        }
        catch(Exception e){}
    }
    
    private void xoa_ve(){
        hk_id.setText("");
        hk_ht.setText("");
        cb_id.setText("");
        hk_shc.setText("");
        dv_sl.setText("");
        dv_ngaydat.setText("");
    }
    private void hk_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hk_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hk_idActionPerformed

    private void dv_slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dv_slActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dv_slActionPerformed

    private void quaylai_nutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylai_nutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaylai_nutActionPerformed

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huyActionPerformed

    private void datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datActionPerformed
        if(hk_id.getText().isEmpty() || hk_ht.getText().isEmpty() || hk_shc.getText().isEmpty() || cb_id.getText().isEmpty() || dv_sl.getText().isEmpty() || dv_ngaydat.getText().isEmpty())
       {
            JOptionPane.showMessageDialog(this,"Nhập thiếu");
        }
       
    }//GEN-LAST:event_datActionPerformed

    private void dt_ngaymaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_ngaymaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt_ngaymaxActionPerformed

    private void dt_ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_ngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt_ngayActionPerformed
    
    private void datMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datMouseClicked
       if(hk_id.getText().isEmpty() || hk_ht.getText().isEmpty() || hk_shc.getText().isEmpty() || cb_id.getText().isEmpty() || dv_sl.getText().isEmpty() || dv_ngaydat.getText().isEmpty())
       {
            JOptionPane.showMessageDialog(this,"Nhập thiếu");
        }else{
            try {
                dem_ve();
                String connStr="jdbc:mysql://localhost/ariline_data?user=root";
                Connection conn = DriverManager.getConnection(connStr);
                CallableStatement cStmt10 = conn.prepareCall("{call datve(?,?,?,?,?,?,?,?,?)}");
                cStmt10.setInt(1, dem);
                cStmt10.setString(2, hk_id.getText());
                cStmt10.setString(3, hk_ht.getText());
                cStmt10.setString(4, cb_id.getText());
                cStmt10.setString(5, hk_shc.getText());
                cStmt10.setString(6, hk_qt.getSelectedItem().toString()); 
                cStmt10.setString(7, dv_sl.getText());
                cStmt10.setString(8, dv_ngaydat.getText());
                cStmt10.setString(9, lv_loai.getSelectedItem().toString());
                cStmt10.execute();
                ResultSet rs10 = cStmt10.executeQuery("SELECT * FROM ql_datve  ");//join ql_hanhkhach on ql_hanhkhach.HK_id=ql_datve.HK_id
                JOptionPane.showMessageDialog(this,"Đã đặt vé");
                conn.close();
                hienthi_dv();
                key=0;
                xoa_ve();
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        };
    }//GEN-LAST:event_datMouseClicked
    private void hienthi_dv(){
        try{
          conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
          Stmt = conn.createStatement();
          rs=Stmt.executeQuery("Select * from ql_datve");
          dsdv.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e){   
        }
    }
    int key=0;
    private void huyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huyMouseClicked
        if(key==0){
            JOptionPane.showMessageDialog(this,"Chọn 1 vé");
        }
        else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
                CallableStatement cStmt11 = conn.prepareCall("{call huyve(?)}");
                cStmt11.setInt(1, key);
                cStmt11.execute();
                ResultSet rs11 = cStmt11.executeQuery("SELECT * FROM ql_datve");
                key=0;
                JOptionPane.showMessageDialog(this,"Đã xoá vé");
                xoa_ve(); 
                hienthi_dv();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_huyMouseClicked

    private void quaylai_nutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quaylai_nutMouseClicked
        new chon_dv().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quaylai_nutMouseClicked

    private void dsdvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsdvMouseClicked
                DefaultTableModel model=(DefaultTableModel)dsdv.getModel();
                int myindex=dsdv.getSelectedRow();
                key=Integer.valueOf(model.getValueAt(myindex,0).toString());
                hk_id.setText(model.getValueAt(myindex,1).toString());
                hk_ht.setText(model.getValueAt(myindex,2).toString());
                cb_id.setText(model.getValueAt(myindex,3).toString());
                hk_shc.setText(model.getValueAt(myindex,4).toString());
                hk_qt.setSelectedItem(model.getValueAt(myindex,5).toString());
                dv_sl.setText(model.getValueAt(myindex,6).toString());
                dv_ngaydat.setText(model.getValueAt(myindex,7).toString());
                lv_loai.setSelectedItem(model.getValueAt(myindex,8).toString());
              
    }//GEN-LAST:event_dsdvMouseClicked

    private void lv_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lv_loaiActionPerformed
       // tim_loaive();
    }//GEN-LAST:event_lv_loaiActionPerformed
    
    private void tim_loaive(){
       try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
         Stmt = conn.createStatement();
         rs=Stmt.executeQuery("select * from ql_datve where LV_loai= '"+loc_lv.getSelectedItem().toString()+"'");
         dsdv.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch (Exception e){
       }
    }
    private void tinh_tienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinh_tienActionPerformed
         tinhtien();
    }//GEN-LAST:event_tinh_tienActionPerformed
    private void chuacove(){
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
            Stmt = conn.createStatement();
            rs=Stmt.executeQuery("select * from ql_hanhkhach where HK_id NOT IN (select distinct HK_id from ql_datve)");
            dsdv.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e){
       }
    }
    private void hk_chuacoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hk_chuacoveActionPerformed
        chuacove();
    }//GEN-LAST:event_hk_chuacoveActionPerformed

    private void lam_moiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lam_moiMouseClicked
        hienthi_dv();
        xoa_ve();
        tim_ve.setText("");
    }//GEN-LAST:event_lam_moiMouseClicked

    private void lam_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lam_moiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lam_moiActionPerformed

    private void ud_veMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ud_veMouseClicked
        if(key==0 || hk_id.getText().isEmpty() || hk_ht.getText().isEmpty() || hk_shc.getText().isEmpty() || cb_id.getText().isEmpty() || dv_sl.getText().isEmpty() || dv_ngaydat.getText().isEmpty())
       {
            JOptionPane.showMessageDialog(this,"Chọn 1 vé");
        }
        else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
                PreparedStatement Ud=conn.prepareStatement("Update ql_datve set HK_id=?, HK_ten=?, CB_id=?, HK_sohochieu=?, HK_quoctich=? , DV_soluong=?, DV_ngaydat=?, LV_loai=? where DV_id=?");
                Ud.setInt(9, key);
                Ud.setString(1, hk_id.getText());
                Ud.setString(2, hk_ht.getText());
                Ud.setString(3, cb_id.getText());
                Ud.setString(4, hk_shc.getText());
                Ud.setString(5, hk_qt.getSelectedItem().toString()); 
                Ud.setString(6, dv_sl.getText());
                Ud.setString(7, dv_ngaydat.getText());
                Ud.setString(8, lv_loai.getSelectedItem().toString());
                int row=Ud.executeUpdate();
                JOptionPane.showMessageDialog(this,"Đã cập nhật hành khách");
                conn.close();
                hienthi_dv();
                key=0;
                xoa_ve();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_ud_veMouseClicked

    private void ud_veActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ud_veActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ud_veActionPerformed

    private void hk_qtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hk_qtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hk_qtActionPerformed

    private void hk_shcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hk_shcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hk_shcActionPerformed

    private void hk_htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hk_htActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hk_htActionPerformed
    private void search_ve(){
           try{
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ariline_data?user=root");
             Stmt = conn.createStatement();
             rs=Stmt.executeQuery("Select * from ql_datve where DV_id like '"+tim_ve.getText()+"%'");
             dsdv.setModel(DbUtils.resultSetToTableModel(rs));
           }
           catch (Exception e){
           }
    }
    private void tim_veCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tim_veCaretUpdate
        search_ve();
    }//GEN-LAST:event_tim_veCaretUpdate

    private void tim_veActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tim_veActionPerformed
        search_ve();
    }//GEN-LAST:event_tim_veActionPerformed
    
    private void dt_ngay(){
        try{
            CallableStatement cStmt24 = conn.prepareCall("{?=call doanhthu_ngay(DV_ngaydat)}");
            cStmt24.registerOutParameter(1,Types.DOUBLE);     
            cStmt24.executeQuery("select distinct  ql_datve.DV_ngaydat,doanhthu_ngay(DV_ngaydat) from ql_datve where ql_datve.DV_ngaydat=DV_ngaydat");
            ResultSet rs24 = cStmt24.getResultSet();
            dsdv.setModel(DbUtils.resultSetToTableModel(rs24));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }    
    private void dt_ngayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dt_ngayMouseClicked
         dt_ngay();
    }//GEN-LAST:event_dt_ngayMouseClicked

    private void loc_lvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loc_lvItemStateChanged

    }//GEN-LAST:event_loc_lvItemStateChanged

    private void loc_lvCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_loc_lvCaretPositionChanged
        JOptionPane.showMessageDialog(this,"Không có");
    }//GEN-LAST:event_loc_lvCaretPositionChanged

    private void loc_lvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_lvActionPerformed
        tim_loaive();
    }//GEN-LAST:event_loc_lvActionPerformed

    private void loc_lvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loc_lvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loc_lvMouseClicked

    private void tinh_tienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tinh_tienMouseClicked
       tinhtien();
    }//GEN-LAST:event_tinh_tienMouseClicked
    private void dt_ngaymax(){
        try{
            CallableStatement cStmt24 = conn.prepareCall("{?=call doanhthu_ngaymax(DV_ngaydat)}");
            cStmt24.registerOutParameter(1,Types.DOUBLE);     
            cStmt24.executeQuery("select distinct  ql_datve.DV_ngaydat,max(doanhthu_ngay(DV_ngaydat))as doanhthu_ngaymax from ql_datve where ql_datve.DV_ngaydat=DV_ngaydat");
            ResultSet rs24 = cStmt24.getResultSet();
            dsdv.setModel(DbUtils.resultSetToTableModel(rs24));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }    
    private void dt_ngaymaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dt_ngaymaxMouseClicked
        dt_ngaymax();
    }//GEN-LAST:event_dt_ngaymaxMouseClicked

    private void loaiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaiveMouseClicked
        new loai_ve().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loaiveMouseClicked

    private void print_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_cbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_print_cbMouseClicked

    private void print_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_cbActionPerformed
        MessageFormat header = new MessageFormat("Bảng in danh sách các vé");
        MessageFormat footer = new MessageFormat("Trang {0, number, integer}");
        try{
            dsdv.print(JTable.PrintMode.NORMAL,header, footer);
        }
        catch(java.awt.print.PrinterAbortException e){
            System.err.format("No Printer found", e.getMessage());
        } catch (PrinterException ex) {
            Logger.getLogger(ql_chuyenbay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_cbActionPerformed

    private void thoat_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoat_cbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_thoat_cbMouseClicked

    private void thoat_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat_cbActionPerformed
        frame = new JFrame("Thoát");
        if (JOptionPane.showConfirmDialog(frame, "Xác nhận nếu bạn muốn thoát","Hệ thống đặt vé máy bay",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_thoat_cbActionPerformed
    private void tinhtien(){
        try{
            CallableStatement cStmt24 = conn.prepareCall("{?=call tinh_tien(DV_id)}");
            cStmt24.registerOutParameter(1,Types.DOUBLE);     
            cStmt24.executeQuery("select DV_id,HK_id,HK_ten,CB_id, DV_soluong,ql_datve.LV_loai, DV_soluong*(LV_gia+LV_phipv+LV_phuthu+((LV_gia+LV_phipv+LV_phuthu)*0.1)) as tra_tien from ql_datve inner join ql_loaive on ql_datve.LV_loai=ql_loaive.LV_loai ORDER BY DV_id ASC");
            ResultSet rs24 = cStmt24.getResultSet();
            dsdv.setModel(DbUtils.resultSetToTableModel(rs24));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ql_ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ql_ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ql_ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ql_ve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ql_ve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cb_id;
    private javax.swing.JButton dat;
    private javax.swing.JTable dsdv;
    private javax.swing.JRadioButton dt_ngay;
    private javax.swing.JRadioButton dt_ngaymax;
    private javax.swing.JTextField dv_ngaydat;
    private javax.swing.JTextField dv_sl;
    private javax.swing.JRadioButton hk_chuacove;
    private javax.swing.JTextField hk_ht;
    private javax.swing.JTextField hk_id;
    private javax.swing.JComboBox<String> hk_qt;
    private javax.swing.JTextField hk_shc;
    private javax.swing.JButton huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lam_moi;
    private javax.swing.JButton loaive;
    private javax.swing.JComboBox<String> loc_lv;
    private javax.swing.JComboBox<String> lv_loai;
    private javax.swing.JButton print_cb;
    private javax.swing.JButton quaylai_nut;
    private javax.swing.JButton thoat_cb;
    private javax.swing.JTextField tim_ve;
    private javax.swing.JRadioButton tinh_tien;
    private javax.swing.JButton ud_ve;
    // End of variables declaration//GEN-END:variables
}
